Daily_Services/Controllers/AcademicController.cs
using Daily_Services.Models;
using System.Linq;
using System.Web.Mvc;

namespace Daily_Services.Controllers
{
    public class AcademicController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Academic
        public ActionResult AcademicSubCategories()
        {
            var list = db.GetSubCategories.Where(x => x.Category_Id == 2).ToList();
            return View(list);
        }
    }
}

Daily_Services/Controllers/ServiceProviderController.cs
using Daily_Services.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Daily_Services.Controllers
{
    public class ServiceProviderController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: ServiceProvider
        public ActionResult Academic()
        {
            ViewBag.Category_Id = new SelectList(db.Categories, "Category_Id", "Category_Type");
            ViewBag.Gender_Id = new SelectList(db.Genders, "Gender_Id", "Gender_Type");
            ViewBag.Qualification_Id = new SelectList(db.Qualifications, "Qualification_Id", "Qualification_Type");
            List<ApplicationUser> registrations = db.Users.Where(r => r.Category_Id == 2).ToList();
            ViewBag.AcadmicList = registrations;

            return View();
        }


        public ActionResult AcademicDetail(string id)
        {
          
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
          ApplicationUser registration = db.Users.Find(id);
            if (registration == null)
            {
                return HttpNotFound();
            }
            return View(registration);
        }
    }
}

Daily_Services/Views/ServiceProvider/Academic.cshtml
@model  Daily_Services.Models.ApplicationUser
@{
    /**/

    ViewBag.Title = "Show";
}
<head>
    <meta charset="UTF-8">
    <title>Profile cards animated with CSS3</title>
    <link href="http://fonts.googleapis.com/css?family=Lato:100,900" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="css/style.css" />
    <script src="prefixfree.min.js"></script>
</head>
<div>
    <div id="wrapper" class="container">
        <br />
        <h3>Academic Records</h3>
        <br />

        <div id="content">
            <div class="row">
                @foreach (var item in ViewBag.AcadmicList)
                {
                   
                    <a href="~/ServiceProvider/AcademicDetail/@item.Id">
                        <div class="col-md-3">
                            <div class="img-thumbnail" style="margin-bottom:10px">
                                <img class="pic" src="/images/@item.Image_Path" alt="Mia" style="height:250px; width:100%" />
                                <b>
                                    @item.First_Name &nbsp;
                                    @item.Last_Name<br />
                                    @item.SubCategory.SubCategory_Type<br />
                                    @*@Html.DisplayFor(modelItem => item.Last_Name)*@
                                </b>
                                <b>
                                    @*@Html.DisplayFor(modelItem => item.SubCategory.SubCategory_Type)*@
                                </b>
                                @Html.ActionLink("AcadmicDetail", "AcademicDetail", "ServiceProvider", new { id = item.Id })<br />
                                @*@Html.ActionLink("Appointment", "Appointment", new { id = item.AppID })*@
                            </div>
                        </div>
                    </a>

                }
            </div>
        </div>
    </div>
</div>